# Generated by Django 4.2.13 on 2024-10-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="sold",
            field=models.BooleanField(default=False),
        ),
    ]
