# Generated by Django 4.2.13 on 2024-10-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_product_is_new_product_sold"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="has_offer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="offer_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
